databases:
  - name: hospital_db
    databaseName: hospital_db
    user: hospital_user

services:
  - type: web
    name: hospital_system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hospital_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospital_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true