# Generated by Django 6.0.4 on 2026-06-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_specialization_doctor_is_available_doctor_shift_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.doctor'),
        ),
    ]
