# Generated by Django 6.0.4 on 2026-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_medicine_batch_number_medicine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20),
        ),
    ]
