# Generated by Django 6.0.4 on 2026-06-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_admission_discharge_date_admission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='admission',
            name='expected_discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.bed'),
        ),
    ]
