# Generated by Django 6.0.4 on 2026-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_admission_doctor_admission_expected_discharge_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacysale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
